// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FNzctUB1fKGDF_riKtIOMkLPUNl_BhI',
    appId: '1:507169574109:web:d736384d8643c489555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    authDomain: 'fir-flutter-auth-cdff2.firebaseapp.com',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqk_HeIFKM0xjOmMsqKzGx86VfEtS4Eg',
    appId: '1:507169574109:android:227a76a4bba3251d555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPJNrfACG3fJ4Z4anQ53rUJxqlrqAk3kw',
    appId: '1:507169574109:ios:514a649121d5d0a0555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
    iosClientId: '507169574109-q2viqe82nvd3rhuvp7b890tareq9a90s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPJNrfACG3fJ4Z4anQ53rUJxqlrqAk3kw',
    appId: '1:507169574109:ios:514a649121d5d0a0555f34',
    messagingSenderId: '507169574109',
    projectId: 'fir-flutter-auth-cdff2',
    storageBucket: 'fir-flutter-auth-cdff2.appspot.com',
    iosClientId: '507169574109-q2viqe82nvd3rhuvp7b890tareq9a90s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
